
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=false

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:https://*.vercel.app,https://connectplus.app.br}


livekit.url=${LIVEKIT_URL:ws://localhost:7880}
livekit.api-key=${LIVEKIT_API_KEY:devkey}
livekit.api-secret=${LIVEKIT_API_SECRET:secret}


logging.level.root=INFO
logging.level.conne.connect.connect=INFO
