CREATE TYPE "empresa_status" AS ENUM (
  'ativa',
  'inativa',
  'bloqueada'
);

CREATE TYPE "usuario_status" AS ENUM (
  'ativo',
  'inativo'
);

CREATE TYPE "papel_empresa" AS ENUM (
  'gestor',
  'colaborador',
  'cliente'
);

CREATE TYPE "projeto_status" AS ENUM (
  'planejamento',
  'em_andamento',
  'concluido',
  'cancelado',
  'arquivado'
);

CREATE TYPE "tarefa_status" AS ENUM (
  'pendente',
  'em_andamento',
  'em_revisao',
  'concluida',
  'cancelada',
  'arquivada'
);

CREATE TYPE "dificuldade_tarefa" AS ENUM (
  'facil',
  'medio',
  'dificil'
);

CREATE TYPE "notificacao_tipo" AS ENUM (
  'novo_projeto',
  'nova_tarefa',
  'tarefa_concluida',
  'lembrete_prazo',
  'mensagem',
  'feedback',
  'sistema'
);

CREATE TYPE "transacao_xp_tipo" AS ENUM (
  'ganho',
  'resgate'
);

CREATE TYPE "conversa_tipo" AS ENUM (
  'privada',
  'grupo'
);

CREATE TYPE "mensagem_tipo" AS ENUM (
  'texto',
  'imagem',
  'arquivo',
  'sistema'
);

CREATE TYPE "sala_status" AS ENUM (
  'ativa',
  'encerrada'
);

CREATE TYPE "plano_tipo" AS ENUM (
  'gratuito',
  'premium'
);

CREATE TYPE "assinatura_status" AS ENUM (
  'ativa',
  'cancelada'
);

CREATE TABLE "empresa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "razao_social" varchar(150) NOT NULL,
  "nome_fantasia" varchar(150),
  "cnpj" varchar(18) UNIQUE,
  "status" empresa_status NOT NULL DEFAULT 'ativa',
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "usuario" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(120) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "senha_hash" varchar(255) NOT NULL,
  "status" usuario_status NOT NULL DEFAULT 'ativo',
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "setor" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "usuario_empresa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "usuario_id" int NOT NULL,
  "setor_id" int,
  "papel" papel_empresa NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "equipe" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "equipe_membro" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "equipe_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "criado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "projeto" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "gestor_id" int NOT NULL,
  "nome" varchar(150) NOT NULL,
  "descricao" text,
  "inicio_em" timestamp,
  "fim_prev" timestamp,
  "fim_real" timestamp,
  "status" projeto_status NOT NULL DEFAULT 'planejamento',
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "projeto_equipe" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "projeto_id" int NOT NULL,
  "equipe_id" int NOT NULL,
  "criado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "tarefa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "projeto_id" int NOT NULL,
  "resp_id" int,
  "titulo" varchar(130) NOT NULL,
  "descricao" text,
  "dificuldade" dificuldade_tarefa NOT NULL,
  "status" tarefa_status NOT NULL DEFAULT 'pendente',
  "criado_em" timestamp NOT NULL,
  "prazo" timestamp,
  "concluida_em" timestamp,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "comentario_tarefa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "tarefa_id" int NOT NULL,
  "autor_id" int NOT NULL,
  "conteudo" text NOT NULL,
  "criado_em" timestamp NOT NULL,
  "editado_em" timestamp,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "recompensa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "nome" varchar(70) NOT NULL,
  "descricao" text,
  "xp_req" int NOT NULL,
  "ativa" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "saldo_xp" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "xp_tot" int NOT NULL DEFAULT 0,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "pedido_resgate" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "xp_tot" int NOT NULL,
  "criado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "pedido_resgate_item" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "resgate_id" int NOT NULL,
  "recompensa_id" int NOT NULL,
  "xp_unit" int NOT NULL,
  "qtd" int NOT NULL DEFAULT 1,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "transacao_xp" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "tarefa_id" int,
  "recompensa_id" int,
  "tipo" transacao_xp_tipo NOT NULL,
  "valor" int NOT NULL,
  "observacao" text,
  "criada_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "resgate_recompensa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "recompensa_id" int NOT NULL,
  "transacao_id" int,
  "qtd" int NOT NULL DEFAULT 1,
  "xp_gasto" int NOT NULL,
  "resgatado_em" timestamp NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'resgatado',
  "incluido" date,
  "excluido" date
);

CREATE TABLE "notificacao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "tipo" notificacao_tipo NOT NULL,
  "titulo" varchar(120),
  "mensagem" text NOT NULL,
  "lida" boolean NOT NULL DEFAULT false,
  "criada_em" timestamp NOT NULL,
  "lida_em" timestamp,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "feedback" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "autor_id" int NOT NULL,
  "projeto_id" int,
  "tarefa_id" int,
  "nota" int NOT NULL,
  "comentario" text,
  "criado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "conversa" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "tipo" conversa_tipo NOT NULL,
  "nome" varchar(120),
  "criador_id" int NOT NULL,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "conversa_participante" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "conversa_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "entrou_em" timestamp NOT NULL,
  "saiu_em" timestamp,
  "ativo" boolean NOT NULL DEFAULT true,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "mensagem" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "conversa_id" int NOT NULL,
  "remetente_id" int NOT NULL,
  "tipo" mensagem_tipo NOT NULL DEFAULT 'texto',
  "conteudo" text,
  "enviada_em" timestamp NOT NULL,
  "editada_em" timestamp,
  "excluida_em" timestamp,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "msg_leitura" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mensagem_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "lido_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "msg_anexo" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mensagem_id" int NOT NULL,
  "nome" varchar(255) NOT NULL,
  "url" text NOT NULL,
  "tipo" varchar(50),
  "tamanho" int,
  "enviado_em" timestamp NOT NULL,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "sala_transmissao" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "conversa_id" int,
  "nome" varchar(120),
  "criador_id" int NOT NULL,
  "status" sala_status NOT NULL DEFAULT 'ativa',
  "inicio_em" timestamp NOT NULL,
  "fim_em" timestamp,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "sala_participante" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sala_id" int NOT NULL,
  "usu_emp_id" int NOT NULL,
  "entrou_em" timestamp NOT NULL,
  "saiu_em" timestamp,
  "compart_tela" boolean NOT NULL DEFAULT false,
  "audio_on" boolean NOT NULL DEFAULT true,
  "video_on" boolean NOT NULL DEFAULT false,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "plano" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(60) NOT NULL,
  "tipo" plano_tipo NOT NULL,
  "max_usuarios" int,
  "valor" numeric(10,2) NOT NULL DEFAULT 0,
  "incluido" date,
  "excluido" date
);

CREATE TABLE "assinatura" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" int NOT NULL,
  "plano_id" int NOT NULL,
  "qtd_usuarios" int NOT NULL DEFAULT 1,
  "status" assinatura_status NOT NULL DEFAULT 'ativa',
  "inicio_em" timestamp NOT NULL,
  "fim_em" timestamp,
  "incluido" date,
  "excluido" date
);

CREATE UNIQUE INDEX ON "setor" ("empresa_id", "nome");

CREATE UNIQUE INDEX ON "usuario_empresa" ("empresa_id", "usuario_id");

CREATE UNIQUE INDEX ON "equipe" ("empresa_id", "nome");

CREATE UNIQUE INDEX ON "equipe_membro" ("equipe_id", "usu_emp_id");

CREATE UNIQUE INDEX ON "projeto_equipe" ("projeto_id", "equipe_id");

CREATE INDEX ON "tarefa" ("projeto_id");

CREATE INDEX ON "tarefa" ("resp_id");

CREATE UNIQUE INDEX ON "recompensa" ("empresa_id", "nome");

CREATE UNIQUE INDEX ON "saldo_xp" ("usu_emp_id");

CREATE INDEX ON "notificacao" ("usu_emp_id");

CREATE UNIQUE INDEX ON "conversa_participante" ("conversa_id", "usu_emp_id");

CREATE INDEX ON "mensagem" ("conversa_id", "enviada_em");

CREATE UNIQUE INDEX ON "msg_leitura" ("mensagem_id", "usu_emp_id");

CREATE INDEX ON "sala_transmissao" ("status");

CREATE UNIQUE INDEX ON "sala_participante" ("sala_id", "usu_emp_id");

ALTER TABLE "setor" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_empresa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_empresa" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_empresa" ADD FOREIGN KEY ("setor_id") REFERENCES "setor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe_membro" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe_membro" ADD FOREIGN KEY ("equipe_id") REFERENCES "equipe" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe_membro" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto" ADD FOREIGN KEY ("gestor_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto_equipe" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto_equipe" ADD FOREIGN KEY ("projeto_id") REFERENCES "projeto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto_equipe" ADD FOREIGN KEY ("equipe_id") REFERENCES "equipe" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarefa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarefa" ADD FOREIGN KEY ("projeto_id") REFERENCES "projeto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarefa" ADD FOREIGN KEY ("resp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentario_tarefa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentario_tarefa" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentario_tarefa" ADD FOREIGN KEY ("autor_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recompensa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saldo_xp" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saldo_xp" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate_item" ADD FOREIGN KEY ("resgate_id") REFERENCES "pedido_resgate" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate_item" ADD FOREIGN KEY ("recompensa_id") REFERENCES "recompensa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("recompensa_id") REFERENCES "recompensa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("recompensa_id") REFERENCES "recompensa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("transacao_id") REFERENCES "transacao_xp" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacao" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacao" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("autor_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("projeto_id") REFERENCES "projeto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversa" ADD FOREIGN KEY ("criador_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversa_participante" ADD FOREIGN KEY ("conversa_id") REFERENCES "conversa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "conversa_participante" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensagem" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensagem" ADD FOREIGN KEY ("conversa_id") REFERENCES "conversa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "mensagem" ADD FOREIGN KEY ("remetente_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "msg_leitura" ADD FOREIGN KEY ("mensagem_id") REFERENCES "mensagem" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "msg_leitura" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "msg_anexo" ADD FOREIGN KEY ("mensagem_id") REFERENCES "mensagem" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_transmissao" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_transmissao" ADD FOREIGN KEY ("conversa_id") REFERENCES "conversa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_transmissao" ADD FOREIGN KEY ("criador_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_participante" ADD FOREIGN KEY ("sala_id") REFERENCES "sala_transmissao" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sala_participante" ADD FOREIGN KEY ("usu_emp_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assinatura" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "assinatura" ADD FOREIGN KEY ("plano_id") REFERENCES "plano" ("id") DEFERRABLE INITIALLY IMMEDIATE;
