CREATE TYPE "empresa_status" AS ENUM (
  'ativa',
  'inativa',
  'bloqueada'
);

CREATE TYPE "usuario_status" AS ENUM (
  'ativo',
  'inativo'
);

CREATE TYPE "papel_empresa" AS ENUM (
  'gestor',
  'colaborador',
  'cliente'
);

CREATE TYPE "projeto_status" AS ENUM (
  'planejamento',
  'em_andamento',
  'concluido',
  'cancelado',
  'arquivado'
);

CREATE TYPE "tarefa_status" AS ENUM (
  'pendente',
  'em_andamento',
  'em_revisao',
  'concluida',
  'cancelada',
  'arquivada'
);

CREATE TYPE "dificuldade_tarefa" AS ENUM (
  'facil',
  'medio',
  'dificil'
);

CREATE TYPE "notificacao_tipo" AS ENUM (
  'novo_projeto',
  'nova_tarefa',
  'tarefa_concluida',
  'lembrete_prazo',
  'mensagem',
  'feedback',
  'sistema'
);

CREATE TYPE "transacao_xp_tipo" AS ENUM (
  'ganho',
  'resgate'
);

CREATE TABLE "empresa" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "razao_social" varchar(150) NOT NULL,
  "nome_fantasia" varchar(150),
  "cnpj" varchar(18) UNIQUE,
  "status" empresa_status NOT NULL DEFAULT 'ativa',
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "usuario" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(120) NOT NULL,
  "email" varchar(150) UNIQUE NOT NULL,
  "senha_hash" varchar(255) NOT NULL,
  "status" usuario_status NOT NULL DEFAULT 'ativo',
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "setor" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "usuario_empresa" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "usuario_id" bigint NOT NULL,
  "setor_id" bigint,
  "papel" papel_empresa NOT NULL,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "equipe" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "nome" varchar(100) NOT NULL,
  "descricao" text,
  "ativo" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "equipe_membro" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "equipe_id" bigint NOT NULL,
  "usuario_empresa_id" bigint NOT NULL,
  "criado_em" timestamp NOT NULL
);

CREATE TABLE "projeto" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "gestor_usuario_empresa_id" bigint NOT NULL,
  "nome" varchar(150) NOT NULL,
  "descricao" text,
  "data_inicio" timestamp,
  "data_fim_prevista" timestamp,
  "data_fim_real" timestamp,
  "status" projeto_status NOT NULL DEFAULT 'planejamento',
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "projeto_equipe" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "projeto_id" bigint NOT NULL,
  "equipe_id" bigint NOT NULL,
  "criado_em" timestamp NOT NULL
);

CREATE TABLE "tarefa" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "projeto_id" bigint NOT NULL,
  "responsavel_usuario_empresa_id" bigint,
  "titulo" varchar(130) NOT NULL,
  "descricao" text,
  "dificuldade" dificuldade_tarefa NOT NULL,
  "status" tarefa_status NOT NULL DEFAULT 'pendente',
  "data_criacao" timestamp NOT NULL,
  "prazo" timestamp,
  "concluida_em" timestamp,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "comentario_tarefa" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "tarefa_id" bigint NOT NULL,
  "autor_usuario_empresa_id" bigint NOT NULL,
  "conteudo" text NOT NULL,
  "criado_em" timestamp NOT NULL,
  "editado_em" timestamp
);

CREATE TABLE "recompensa" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "nome" varchar(70) NOT NULL,
  "descricao" text,
  "xp_necessario" int NOT NULL,
  "ativa" boolean NOT NULL DEFAULT true,
  "criado_em" timestamp NOT NULL,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "saldo_xp" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "usuario_empresa_id" bigint NOT NULL,
  "xp_total" int NOT NULL DEFAULT 0,
  "atualizado_em" timestamp NOT NULL
);

CREATE TABLE "pedido_resgate" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "usuario_empresa_id" bigint NOT NULL,
  "xp_total" int NOT NULL,
  "criado_em" timestamp NOT NULL
);

CREATE TABLE "pedido_resgate_item" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pedido_resgate_id" bigint NOT NULL,
  "recompensa_id" bigint NOT NULL,
  "xp_unitario" int NOT NULL,
  "quantidade" int NOT NULL DEFAULT 1
);

CREATE TABLE "transacao_xp" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "usuario_empresa_id" bigint NOT NULL,
  "tarefa_id" bigint,
  "recompensa_id" bigint,
  "tipo" transacao_xp_tipo NOT NULL,
  "valor" int NOT NULL,
  "observacao" text,
  "criada_em" timestamp NOT NULL
);

CREATE TABLE "resgate_recompensa" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "usuario_empresa_id" bigint NOT NULL,
  "recompensa_id" bigint NOT NULL,
  "transacao_xp_id" bigint,
  "quantidade" int NOT NULL DEFAULT 1,
  "xp_gasto" int NOT NULL,
  "resgatado_em" timestamp NOT NULL,
  "status" varchar(30) NOT NULL DEFAULT 'resgatado'
);

CREATE TABLE "notificacao" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "usuario_empresa_id" bigint NOT NULL,
  "tipo" notificacao_tipo NOT NULL,
  "titulo" varchar(120),
  "mensagem" text NOT NULL,
  "lida" boolean NOT NULL DEFAULT false,
  "criada_em" timestamp NOT NULL,
  "lida_em" timestamp
);

CREATE TABLE "feedback" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "empresa_id" bigint NOT NULL,
  "autor_usuario_empresa_id" bigint NOT NULL,
  "projeto_id" bigint,
  "tarefa_id" bigint,
  "nota" int NOT NULL,
  "comentario" text,
  "criado_em" timestamp NOT NULL
);

CREATE UNIQUE INDEX ON "setor" ("empresa_id", "nome");

CREATE UNIQUE INDEX ON "usuario_empresa" ("empresa_id", "usuario_id");

CREATE INDEX ON "usuario_empresa" ("empresa_id", "papel");

CREATE UNIQUE INDEX ON "equipe" ("empresa_id", "nome");

CREATE UNIQUE INDEX ON "equipe_membro" ("equipe_id", "usuario_empresa_id");

CREATE INDEX ON "equipe_membro" ("empresa_id", "equipe_id");

CREATE INDEX ON "projeto" ("empresa_id", "nome");

CREATE INDEX ON "projeto" ("empresa_id", "status");

CREATE UNIQUE INDEX ON "projeto_equipe" ("projeto_id", "equipe_id");

CREATE INDEX ON "projeto_equipe" ("empresa_id", "projeto_id");

CREATE INDEX ON "tarefa" ("empresa_id", "projeto_id");

CREATE INDEX ON "tarefa" ("empresa_id", "responsavel_usuario_empresa_id");

CREATE INDEX ON "tarefa" ("empresa_id", "status");

CREATE INDEX ON "comentario_tarefa" ("empresa_id", "tarefa_id");

CREATE UNIQUE INDEX ON "recompensa" ("empresa_id", "nome");

CREATE UNIQUE INDEX ON "saldo_xp" ("usuario_empresa_id");

CREATE INDEX ON "transacao_xp" ("empresa_id", "usuario_empresa_id");

CREATE INDEX ON "transacao_xp" ("empresa_id", "tipo");

CREATE INDEX ON "resgate_recompensa" ("empresa_id", "usuario_empresa_id");

CREATE INDEX ON "resgate_recompensa" ("empresa_id", "recompensa_id");

CREATE INDEX ON "notificacao" ("empresa_id", "usuario_empresa_id");

CREATE INDEX ON "notificacao" ("empresa_id", "lida");

CREATE INDEX ON "feedback" ("empresa_id", "projeto_id");

CREATE INDEX ON "feedback" ("empresa_id", "tarefa_id");

ALTER TABLE "setor" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_empresa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_empresa" ADD FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario_empresa" ADD FOREIGN KEY ("setor_id") REFERENCES "setor" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe_membro" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe_membro" ADD FOREIGN KEY ("equipe_id") REFERENCES "equipe" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "equipe_membro" ADD FOREIGN KEY ("usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto" ADD FOREIGN KEY ("gestor_usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto_equipe" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto_equipe" ADD FOREIGN KEY ("projeto_id") REFERENCES "projeto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "projeto_equipe" ADD FOREIGN KEY ("equipe_id") REFERENCES "equipe" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarefa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarefa" ADD FOREIGN KEY ("projeto_id") REFERENCES "projeto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tarefa" ADD FOREIGN KEY ("responsavel_usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentario_tarefa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentario_tarefa" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comentario_tarefa" ADD FOREIGN KEY ("autor_usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recompensa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saldo_xp" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "saldo_xp" ADD FOREIGN KEY ("usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate" ADD FOREIGN KEY ("usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate_item" ADD FOREIGN KEY ("pedido_resgate_id") REFERENCES "pedido_resgate" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pedido_resgate_item" ADD FOREIGN KEY ("recompensa_id") REFERENCES "recompensa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "transacao_xp" ADD FOREIGN KEY ("recompensa_id") REFERENCES "recompensa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("recompensa_id") REFERENCES "recompensa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "resgate_recompensa" ADD FOREIGN KEY ("transacao_xp_id") REFERENCES "transacao_xp" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacao" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacao" ADD FOREIGN KEY ("usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("empresa_id") REFERENCES "empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("autor_usuario_empresa_id") REFERENCES "usuario_empresa" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("projeto_id") REFERENCES "projeto" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "feedback" ADD FOREIGN KEY ("tarefa_id") REFERENCES "tarefa" ("id") DEFERRABLE INITIALLY IMMEDIATE;
