spring.application.name=Connect+
server.port=8020

spring.datasource.url=jdbc:postgresql://localhost:5432/Conncect-plus

spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:123456987}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false